config/routes.rb
Rails.application.routes.draw do
  
  root 'accounts#index'

  devise_for :users
  
  resources :accounts

end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user

  validates :balance, numericality: { greater_than_or_equal_to: 25, message: 
  "Must be at least a $25 deposit" }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :accounts
  
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  def index
    @accounts = current_user.accounts 
  end

  def show
  end

  def new
    @account = current_user.accounts.new
  end

  def create
    @account = current_user.accounts.new(account_params)
    if @account.save
      flash[:success] = "Account created"
      redirect_to accounts_path
    else
      flash[:error] = "Error #{@account.errors.messages[:balance][0]}"
      render :new
    end
  end

  def edit
  end

  def update 
    if @account.update(account_params)
      redirect_to accounts_path
    else
      render :edit
    end
  end

  def destroy
    @account.destroy
    redirect_to accounts_path
  end

  private
    def account_params
      params.require(:account).permit(:name, :balance)
    end

    def set_account
      # Don't use Account model or you may potentially be able to view or change other accounts
      @account = current_user.accounts.find(params[:id])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    end


end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/edit.html.erb
<h1>Accounts#edit</h1>
<p>Find me in app/views/accounts/edit.html.erb</p>

app/views/accounts/index.html.erb
<%= button_to "Log Out", destroy_user_session_path, method: :delete %>
<h2>Welcome <%= current_user.first_name %></h2>
<hr />
<%= link_to 'Add account', new_account_path %>
<h3>Your Accounts</h3>
<ul>
  <% @accounts.each do |account| %>
    <li>
      <%= account.name %> - <%= account.balance %>
    </li>
  <% end %>
</ul> 

app/views/accounts/new.html.erb
<h1>Add Account</h1>
<%= form_with(model: @account, local: true, class: 'form') do |f| %>
  <div class='field'>
    <%= f.label :name %>
    <%= f.text_field :name, required: true %>
  </div>

  <div class='field'>
    <%= f.label :balance %>
    <%= f.number_field :balance, required: true, min: 0 %>
  </div>

  <%= f.submit %>
<% end %>

app/views/accounts/show.html.erb
<h1>Accounts#show</h1>
<p>Find me in app/views/accounts/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBank</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
  <div class='container'>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key%>%">
      <%= value %>
      </div>
    <% end %>
      <%= yield %>

    
  </body>
</html>